#!D:\End To End DL Project\End-To-End-Kidney-Disease-Classification-Deep-Learning-Project-\tfenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
